name: schedron
description: A parser and evaluator for the Schedron scheduling language.
version: 0.1.0
repository: https://github.com/BjWe/schedron_dart
issue_tracker: https://github.com/BjWe/schedron_dart/issues
license: MIT

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: ^1.24.0
